service: cca-serverless

provider:
  environment:
    AWS_ACCOUNT_ID: ${opt:aws-account-id}
    INITIALS: ${opt:initials}
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Action:
        - 's3:ListBucket'
      Effect: Allow
      Resource:
        - 'arn:aws:s3:::${opt:initials}-cca-ted-raw-${opt:stage}'
    - Action:
        - 's3:*Object'
      Effect: Allow
      Resource:
        - 'arn:aws:s3:::${opt:initials}-cca-ted-extracted-${opt:stage}/*'
        - 'arn:aws:s3:::${opt:initials}-cca-ted-raw-${opt:stage}/*'
    - Action:
        - 'sqs:*Message'
      Effect: Allow
      Resource:
        - 'arn:aws:sqs:eu-west-1:${opt:aws-account-id}:${opt:initials}_cca_ted_extractions_${opt:stage}'
        - 'arn:aws:sqs:eu-west-1:${opt:aws-account-id}:${opt:initials}_cca_ted_transfers_${opt:stage}'
  name: aws
  region: eu-west-1
  runtime: python3.7

functions:
  process_extractions:
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-1:${opt:aws-account-id}:${opt:initials}_cca_ted_extractions_${opt:stage}
          batchSize: 3
    handler: batch_job.process_extractions
    layers:
      - arn:aws:lambda:eu-west-1:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:${opt:layers-version}
    timeout: 900
  process_transfers:
    events:
      - sqs: arn:aws:sqs:eu-west-1:${opt:aws-account-id}:${opt:initials}_cca_ted_transfers_${opt:stage}
    handler: batch_job.process_transfers
    layers:
      - arn:aws:lambda:eu-west-1:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:${opt:layers-version}
    reservedConcurrency: 2
    timeout: 900
  start_extract_job:
    handler: batch_job.start_extract_job
    layers:
      - arn:aws:lambda:eu-west-1:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:${opt:layers-version}
    timeout: 900
  start_transfer_job:
    handler: batch_job.start_transfer_job
    layers:
      - arn:aws:lambda:eu-west-1:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:${opt:layers-version}
    timeout: 900

plugins:
  - serverless-python-requirements