service: cca-serverless

provider:
  environment:
    INITIALS: ${opt:initials}
    STAGE: ${opt:stage}
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - 's3:GetBucketNotification'
         - 's3:PutBucketNotification'
       Resource:
         - 'arn:aws:s3:::${opt:initials}-cca-ted-raw-${opt:stage}'
  name: aws
  region: eu-west-3
  runtime: python3.7

functions:
  extract_data:
    events:
      - existingS3: 
          bucket: ${opt:initials}-cca-ted-raw-${opt:stage}
          events:
            - s3:ObjectCreated:*
    handler: extract_xml_lambda.lambda_handler
    layers:
      - arn:aws:lambda:eu-west-3:725598214641:layer:numpy-pandas-pyarrow-pytz:1
  hello:
    handler: handler.hello

plugins:
  - serverless-plugin-existing-s3
  - serverless-python-requirements