service: cca-serverless

provider:
  environment:
    AWS_ACCOUNT_ID: ${opt:aws-account-id}
    INITIALS: ${opt:initials}
    STAGE: ${opt:stage}
  iamRoleStatements:
    - Action:
        - 's3:GetBucketNotification'
        - 's3:PutBucketNotification'
      Effect: Allow
      Resource:
        - 'arn:aws:s3:::${opt:initials}-cca-ted-raw-${opt:stage}'
    - Action:
        - 's3:*Object'
      Effect: Allow
      Resource:
        - 'arn:aws:s3:::${opt:initials}-cca-ted-raw-${opt:stage}/*'
        - 'arn:aws:s3:::${opt:initials}-cca-ted-extracted-${opt:stage}/*'
    - Action:
        - 'sqs:*Message'
      Effect: Allow
      Resource:
        - 'arn:aws:sqs:eu-west-1:${opt:aws-account-id}:${opt:initials}_cca_ted_batch_job_${opt:stage}'
  name: aws
  region: eu-west-1
  runtime: python3.7

functions:
  # extract_data:
  #   events:
  #     - existingS3: 
  #         bucket: ${opt:initials}-cca-ted-raw-${opt:stage}
  #         events:
  #           - s3:ObjectCreated:*
  #   handler: extract_xml_lambda.lambda_handler
  #   layers:
  #     - arn:aws:lambda:eu-west-3:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:2
  start_batch_job:
    handler: batch_job.start
    layers:
      - arn:aws:lambda:eu-west-1:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:1
  process_batch:
    events:
      - sqs: arn:aws:sqs:eu-west-1:${opt:aws-account-id}:${opt:initials}_cca_ted_batch_job_${opt:stage}
    handler: batch_job.process_batch
    layers:
      # TODO Don't hardcode the region
      - arn:aws:lambda:eu-west-1:${opt:aws-account-id}:layer:numpy-pandas-pyarrow-pytz:1
    reservedConcurrency: 2
    timeout: 900

plugins:
  - serverless-plugin-existing-s3
  - serverless-python-requirements